apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wftin9dvy-nodejs 
  janus-idp.io/tekton: wftin9dvy-nodejs
  backstage.io/kubernetes-id: wftin9dvy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wftin9dvy-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml