apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wftin9dvy-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wftin9dvy-nodejs 
  name: wftin9dvy-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wftin9dvy-nodejs 
